### ISSUE TITLE
Publish ZIP logs to GitHub Releases (instead of GHPR)

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit-testdata#4]
The current way of consuming these logs is not ideal as it requires hoops with GitHub Package Registry, both from publishing, but most importantly with consuming (and testing) in `gctoolkit`.

I'd suggest we simply publish these logs as a single ZIP file under this project's Releases, and then use Wagon plugin [1] to download it during the gctoolkit's `pre-integration-test phase`.

[1] https://www.mojohaus.org/wagon-maven-plugin/

**Comment by brunoborges** [comment]
// @karianna @dsgrieve @kirk-microsoft @johnoliver

**Comment by dsgrieve** [comment]
This is exactly what happens now. Almost. The files are packaged as zip files. It just happens that there are four of them. I'm not sure I understand how having one zip solves the github packaging hoops. It might be helpful to point out what those hoops are.

**Comment by brunoborges** [comment]
ZIP files can simply be published as a GitHub Release, instead of a managed Maven artifact (GitHub Package Registry)
