### ISSUE TITLE
Artifact version in 1.0.2 tag contains -SNAPSHOT

### ISSUE THREAD

**Issue by brunoborges** [microsoft/gctoolkit-testdata#6]
The pom files in 1.0.2 tag (and likely the previous tag) contain -SNAPSHOT in the version.

**Comment by brunoborges** [comment]
See https://github.com/microsoft/gctoolkit-testdata/tree/1.0.2

**Comment by dsgrieve** [comment]
I'm not sure I understand. The pom files in the packages are correct. I don't see -SNAPSHOT.

**Comment by brunoborges** [comment]
Only for the ones published on the GitHub Package Registry. But the source code **tag** for version 1.0.2, contains `-SNAPSHOT`.

It shouldn't.
